import 'server-only'
import { mkdir, readFile, rm, writeFile } from 'fs/promises'
import path from 'path'
import { del, get, put } from '@vercel/blob'

/**
 * Where attachment files live. Files are never public: they are only served
 * through /api/files/[id], which checks who may see them.
 *
 * - Vercel Blob (private store) when BLOB_READ_WRITE_TOKEN is set — the
 *   deployed app, whose own disk is temporary.
 * - Otherwise a local folder outside /public (STORAGE_DIR, default .data/uploads).
 */
export interface FileStorage {
  put(key: string, data: Buffer, contentType: string): Promise<void>
  /** The file's bytes as a stream, or null if it doesn't exist */
  get(key: string): Promise<ReadableStream<Uint8Array> | null>
  delete(key: string): Promise<void>
}

const blobStorage: FileStorage = {
  async put(key, data, contentType) {
    await put(key, data, { access: 'private', contentType, addRandomSuffix: false })
  },
  async get(key) {
    const result = await get(key, { access: 'private' })
    return result?.statusCode === 200 ? result.stream : null
  },
  async delete(key) {
    await del(key)
  },
}

function localStorage(dir: string): FileStorage {
  // Keys are generated by the server, but never let one escape the folder
  const fileFor = (key: string) => {
    const file = path.resolve(dir, key)
    if (!file.startsWith(path.resolve(dir) + path.sep)) throw new Error('Invalid storage key')
    return file
  }
  return {
    async put(key, data) {
      await mkdir(dir, { recursive: true })
      await writeFile(fileFor(key), data)
    },
    async get(key) {
      try {
        const data = await readFile(fileFor(key))
        return new Blob([new Uint8Array(data)]).stream()
      } catch {
        return null
      }
    },
    async delete(key) {
      await rm(fileFor(key), { force: true })
    },
  }
}

export function getStorage(): FileStorage {
  if (process.env.BLOB_READ_WRITE_TOKEN) return blobStorage
  // A fixed default keeps the build from tracing the whole project into the server bundle
  const dir = process.env.STORAGE_DIR ? path.resolve(process.env.STORAGE_DIR) : path.join(process.cwd(), '.data', 'uploads')
  return localStorage(dir)
}
